---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-password
  namespace: default
spec:
  encryptedData:
    password: AgCiasZ6LKPYXx1boRatEd6AsZXBRJpIZ7G88vgYzNF3r0uAcm75YF4pmXaQ2HOzrqiGnyoRYPGFUI2RpoulihMMQ0cv0+Quyav/PcfkXbrwYKyPlYbXY26F+pSUrpcRqQsujnq/fdXK55YOw4tPskAMs9gQOYK3oQILhEFCy5kwTbnwA/B2tPwnEYg/fbvY80/0H4J4Yw2zyxloXIjNOueCw4YhpW9+CuYWmilQoLFCqZFgOakUlZUTqfx8yInR/s2x5T712G6f7KV9kQuqzVdsfuXwtCBmWHz+BmW+uYWbyhm/ygKJjAdYMseOUSUcvxdf3lqf6YNQAw1FpiNLwML47Bik2xcEb0W8K3+GHGXgygRFqyQzltVGQWv5Vt/6R7TbGbedf7dsxvsP3XIVohqAiF4Y83xdHZWTlcjvgjggdmAY3AyaXhLwVHsO7LdiMzmBzwQHL+LMsw1oaA9xSl87Sbo3TAUUgUg8MdwCzS40jtr8MbPaKsVW6KSl8K42u4Fi5QyrkMnjIC+NZiDv8vqLinV5YNhzEnRhSs+QILegT/thagfrscKbWKvTxhtOnUsKfhdk5T7g1cYR/DkFLq8FznKtEY1g+LeJnb4Fi6j72DW2tbrMkxVFsaaYXetHMbMVkh14dY/QS4ZSP+phe4PWac2Fm9EzPzbh5r+8knTjcj6k44FKFLu9m21g1CtCcF5Y3Z0WYGvdL1e9A/hlrGtRCC84
  template:
    metadata:
      name: db-password
      namespace: default
